"""empty message

Revision ID: 4987f254d468
Revises: faeb220bb71d
Create Date: 2019-11-29 15:45:04.387777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4987f254d468'
down_revision = 'faeb220bb71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tb_user_username', table_name='tb_user')
    op.drop_table('tb_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=256), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_general_ci', length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tb_user_username', 'tb_user', ['username'], unique=True)
    # ### end Alembic commands ###
